apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-istio-v1 #pod name
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworldistio #label for deployment object
        version: v1 #version
    spec:
      containers:
      - name: helloworldistio #name of container
        image: gcr.io/williamscj-istio-demos/istio-hello-world:v1 #gcr image
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8080 #map to container listening port